# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08462d92d642600a63a215f34cfa9e99e53ce74a782327addc8bfa3a41eedb123d34ca3590f0302783fe1fa845131c89cf5e423de88e9985701896e756090a9e

test:
  secret_key_base: a4868a99b11af7675cff5cbe7aa537b92530c6040dba4c6f2b095557e67f96dec78b0f88f3d72624dc4ccfa565b535d6c9937ef459f0c97f19a2404cae8f0efb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
